### ISSUE TITLE
模型推理运行时的hf-dir参数如何设定？

### ISSUE THREAD

**Issue by 2443402965wzw** [yinghuo302/ascend-llm#3]
请问模型推理运行时，执行main.py文件传入的hf-dir参数的tokenizer和模型配置文件是什么？

**Comment by yinghuo302** [comment]
huggingface 上的模型一般都是一个文件夹，里面有config.json 模型配置文件，tokenizer.json tokenizer的配置文件，tokenizer.model tokenizer模型，
![image](https://github.com/user-attachments/assets/9a14b233-f38a-4bbf-a94d-7e2c18c750e0)
